name: build
on:
  push:
    branches: [main]

# action 동작
jobs:
  # OS 환경
  build:
    runs-on: ubuntu-18.04

    steps:
      # 모듈 설치
      - name: Install modules
        run: npm install
      # testcode 실행
      - name: Run test codes
        run: npm run test
      # 빌드
      - name: Build project
        run: npm run build
