name: build
on:
  push:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: npm install
      
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: npm run build
